version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: piyush@123
      MYSQL_DATABASE: Grocery
    ports:
      - "3306:3306" 
    restart: always
    volumes:
      - my-db_7:/var/lib/mysql
  

  web:
    build: ./server
    environment:
      MYSQL_DATABASE: Grocery
      MYSQL_USER: root
      MYSQL_PASSWORD: piyush@123
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json  
    restart: on-failure
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - web
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json    


volumes:
  my-db_7:    